$acermatch = 0
$out1 = " // generated by wmi_struct.ps1 on "
$out1 += (Get-CimInstance -ClassName Win32_ComputerSystem -Property Model | Select-Object -ExpandProperty "Model")
$out2 = "`n`nstatic const struct acer_wmi_class acer_wmi_classes[] = {"
$c1 = 0
$c2 = 0
Get-WmiObject -List -Namespace root/WMI | ForEach-Object {
    $cl2 = ""
    foreach ($q1 in $_.Qualifiers) {
        if ($q1.Name.Equals("Description") -and ($q1.Value.Contains("Version 2.") -or $q1.Value.Contains("Version 1."))) {
            $acermatch = 1
            $c2++
            $cl2 = $_.__CLASS.ToString()
            $out2 += "`n    { // " + $q1.Value
        }
        if ($acermatch -eq 1 -and $q1.Name.Equals("guid")) {
            $out2 += "`n        .guid = `"" + $q1.Value.Substring(1, 36) + "`","
            $out2 += "`n        .name = `"" + $cl2 + "`","
            $out2 += "`n        .methods = &" + $cl2.ToLower() + "_methods,`n    },"
        }
    }
    if ($acermatch -eq 1) {
        $acermatch = 0
        $out1 += "`n`nstatic const struct acer_wmi_method " + $cl2.ToLower() + "_methods[] = {"
        foreach ($m1 in $_.Methods) {
            $c1++
            $out1 += "`n    {"
            foreach ($mq1 in $m1.Qualifiers) {
                if ($mq1.Name.Equals("Description")) {
                    $out1 += " // " + $mq1.Value
                }
                if ($mq1.Name.Equals("WmiMethodId")) {
                    $out1 += "`n        .id   = " + "0x" + $mq1.Value.ToString('X2') + ","
                }
            }
            $out1 += "`n        .name = `"" + $m1.Name + "`","
            $out1 += "`n        .in   = {"
            foreach ($mp1 in $m1.InParameters.Properties) {
                $out1 += "&wmi_t_" + $mp1.Type.ToString().ToLower()
                if ($mp1.IsArray -eq "True") {
                    $out1 += "a"
                }
                $out1 += ","
            }
            $out1 += "NULL},`n        .out  = {"
            foreach ($mp2 in $m1.OutParameters.Properties) {
                $out1 += "&wmi_t_" + $mp2.Type.ToString().ToLower()
                if ($mp2.IsArray -eq "True") {
                    $out1 += "a"
                }
                $out1 += ","
            }
            $out1 += "NULL},`n    },"
        }
        $out1 += "`n    {}`n};"
    }
}
$out1 += "`n`nstatic const size_t acer_wmi_method_count = " + $c1 + ";"
$out2 += "`n    {}`n};`n`nstatic const size_t acer_wmi_class_count = " + $c2 + ";"
Write-Output $out1
Write-Output $out2
