// SPDX-License-Identifier: GPL-2.0-or-later
/*
 *  Acer WMI Laptop Debug
 *
 *  Based on acer-wmi:
 *    Copyright (C) 2005-2007	E.M. Smith
 *    Copyright (C) 2007-2008	Carlos Corbacho <cathectic@gmail.com>
 *    Copyright (C) 2007-2009	Carlos Corbacho <carlos@strangeworlds.co.uk>
 */

#define pr_fmt(fmt) KBUILD_MODNAME ": " fmt

//#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/acpi.h>
#include <linux/debugfs.h>

MODULE_AUTHOR("0x189D7997");
MODULE_DESCRIPTION("Acer Laptop WMI Debug Driver");
MODULE_LICENSE("GPL");

struct debug_wmi_t {
    const bool array;
	const size_t size;
};

struct acer_wmi_method {
	const u32 id;
	const char *const name;
	const struct debug_wmi_t *const in[10];
	const struct debug_wmi_t *const out[10];
};

struct acer_wmi_class {
	const char *const guid;
	const char *const name;
    const struct acer_wmi_method (*const methods)[];
};

#define ACER_WMI_TYPE_ROOT    1
#define ACER_WMI_TYPE_CLASS  2
#define ACER_WMI_TYPE_METHOD 3

typedef u32 acer_wmi_type;

struct acer_wmi_entity {
	acer_wmi_type type;
    const struct acer_wmi_class *class;
    const struct acer_wmi_method *method;
    struct acer_wmi_entity *class_wme;
	struct dentry *dir;
	struct dentry *file;
    char *ret;
    bool read;
};

struct acer_debug {
	struct dentry *root;
    struct acer_wmi_entity *root_wme;
    struct acer_wmi_entity *entities;
};

static const struct debug_wmi_t wmi_t_uint64 = {
    .array = false,
    .size = sizeof(u64),
};

static const struct debug_wmi_t wmi_t_uint32 = {
    .array = false,
    .size = sizeof(u32),
};

static const struct debug_wmi_t wmi_t_uint16 = {
    .array = false,
    .size = sizeof(u16),
};

static const struct debug_wmi_t wmi_t_uint16a = {
    .array = true,
    .size = sizeof(u16),
};

static const struct debug_wmi_t wmi_t_uint8 = {
    .array = false,
    .size = sizeof(u8),
};

static const struct debug_wmi_t wmi_t_uint8a = {
    .array = true,
    .size = sizeof(u8),
};

static const struct debug_wmi_t wmi_t_string = {
    .array = true,
    .size = sizeof(char),
};

 // generated by wmi_struct.ps1 on Predator PHN16S-71

static const struct acer_wmi_method apgeevent_methods[] = {
    {}
};

static const struct acer_wmi_method secevent_methods[] = {
    {}
};

static const struct acer_wmi_method acergenericevent_methods[] = {
    {}
};

static const struct acer_wmi_method apgeaction_methods[] = {
    { // APGe WMI Set Devices Function, Version 2.94
        .id   = 0x01,
        .name = "SetFunction",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // APGe WMI Get Devices Function, Version 2.94
        .id   = 0x02,
        .name = "GetFunction",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    {}
};

static const struct acer_wmi_method batterycontrol_methods[] = {
    { // Get battery Information Interface.
        .id   = 0x13,
        .name = "GetBattInfoInterface",
        .in   = {&wmi_t_uint32,&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Battery Health Control Status.
        .id   = 0x14,
        .name = "GetBatteryHealthControlStatus",
        .in   = {&wmi_t_uint8,&wmi_t_uint8,&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint8,&wmi_t_uint8a,&wmi_t_uint8a,NULL},
    },
    { // Set Battery Health Control.
        .id   = 0x15,
        .name = "SetBatteryHealthControl",
        .in   = {&wmi_t_uint8,&wmi_t_uint8,&wmi_t_uint8,&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint16,&wmi_t_uint16,NULL},
    },
    { // Get Battery Function Data.
        .id   = 0x16,
        .name = "GetBatteryFunctionData",
        .in   = {&wmi_t_uint8,&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint8,&wmi_t_uint8a,&wmi_t_uint8a,&wmi_t_uint8a,NULL},
    },
    { // Set Battery Function Data.
        .id   = 0x17,
        .name = "SetBatteryFunctionData",
        .in   = {&wmi_t_uint8,&wmi_t_uint8,&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint16,NULL},
    },
    {}
};

static const struct acer_wmi_method acergamingfunction_methods[] = {
    { // Set Acer Gaming Profile Configuration.
        .id   = 0x01,
        .name = "SetGamingProfile",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Set Acer Gaming LED Behavior.
        .id   = 0x02,
        .name = "SetGamingLED",
        .in   = {&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Acer Gaming Profile Configuration.
        .id   = 0x03,
        .name = "GetGamingProfile",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Get Acer Gaming LED Behavior.
        .id   = 0x04,
        .name = "GetGamingLED",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint8,NULL},
    },
    { // Get Acer Gaming System Information.
        .id   = 0x05,
        .name = "GetGamingSysInfo",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Set Acer Gaming RGB Keyboard Setting.
        .id   = 0x06,
        .name = "SetGamingRgbKb",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Acer Gaming RGB Keyboard Setting.
        .id   = 0x07,
        .name = "GetGamingRgbKb",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Set Acer Gaming Profile Setting.
        .id   = 0x08,
        .name = "SetGamingProfileSetting",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Acer Gaming Profile Setting.
        .id   = 0x09,
        .name = "GetGamingProfileSetting",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Set Acer Gaming LED Group Behavior.
        .id   = 0x0A,
        .name = "SetGamingLEDBehavior",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Acer Gaming LED Group Behavior.
        .id   = 0x0B,
        .name = "GetGamingLEDBehavior",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Set Acer Gaming LED Group Color.
        .id   = 0x0C,
        .name = "SetGamingLEDColor",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Acer Gaming LED Group Color.
        .id   = 0x0D,
        .name = "GetGamingLEDColor",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Set Acer Gaming Fan Group Behavior.
        .id   = 0x0E,
        .name = "SetGamingFanBehavior",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Acer Gaming Fan Group Behavior.
        .id   = 0x0F,
        .name = "GetGamingFanBehavior",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Set Acer Gaming Fan Group Speed.
        .id   = 0x10,
        .name = "SetGamingFanSpeed",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Acer Gaming Fan Group Speed.
        .id   = 0x11,
        .name = "GetGamingFanSpeed",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Set Acer Gaming Fan Table.
        .id   = 0x12,
        .name = "SetGamingFanTable",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Acer Gaming Fan Table.
        .id   = 0x13,
        .name = "GetGamingFanTable",
        .in   = {NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Set Acer Gaming Keyboard Backlight Behavior.
        .id   = 0x14,
        .name = "SetGamingKBBacklight",
        .in   = {&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Acer Gaming Keyboard Backlight Behavior.
        .id   = 0x15,
        .name = "GetGamingKBBacklight",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint8,NULL},
    },
    { // Set Acer Gaming Miscellaneous Setting.
        .id   = 0x16,
        .name = "SetGamingMiscSetting",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Acer Gaming Miscellaneous Setting.
        .id   = 0x17,
        .name = "GetGamingMiscSetting",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Set CPU Overclocking Profile.
        .id   = 0x18,
        .name = "SetCPUOverclockingProfile",
        .in   = {&wmi_t_uint8,&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint8,NULL},
    },
    { // Get CPU Overclocking Profile.
        .id   = 0x19,
        .name = "GetCPUOverclockingProfile",
        .in   = {&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint8,&wmi_t_uint8,NULL},
    },
    {}
};

static const struct acer_wmi_method datatrans_methods[] = {
    { // APGe WMI Set Data Function, Version 2.94
        .id   = 0x01,
        .name = "SetBIOSSettings",
        .in   = {&wmi_t_uint8,&wmi_t_uint8a,&wmi_t_uint8,&wmi_t_uint8,&wmi_t_uint8,NULL},
        .out  = {&wmi_t_uint16,NULL},
    },
    { // APGe WMI Get Data Function, Version 2.94
        .id   = 0x02,
        .name = "GetBIOSSettings",
        .in   = {&wmi_t_uint8,&wmi_t_uint8a,&wmi_t_uint8,&wmi_t_uint8,&wmi_t_uint8,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_uint16,NULL},
    },
    {}
};

static const struct acer_wmi_method acergenericmethod_methods[] = {
    { // Acer Generic Set Devices Function, Version 2.94
        .id   = 0x01,
        .name = "SetFunction",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Acer Generic Get Devices Function, Version 2.94
        .id   = 0x02,
        .name = "GetFunction",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Acer Generic Get Storage Information, Version 2.94
        .id   = 0x03,
        .name = "GetStorageInformation",
        .in   = {&wmi_t_uint16,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint16a,&wmi_t_uint32,&wmi_t_uint16a,&wmi_t_uint32,&wmi_t_uint16,&wmi_t_uint16,NULL},
    },
    {}
};

static const struct acer_wmi_method longrunfunction_methods[] = {
    { // Long Run Para. Pass to BIOS.
        .id   = 0x01,
        .name = "SetLongRunPara",
        .in   = {&wmi_t_uint8,&wmi_t_uint8,NULL},
        .out  = {&wmi_t_uint16,NULL},
    },
    { // Long Run Para. Pass to BIOS.
        .id   = 0x02,
        .name = "SetFunctionIndex",
        .in   = {&wmi_t_uint8,NULL},
        .out  = {&wmi_t_uint16,NULL},
    },
    { // Long Run Para. Pass to BIOS.
        .id   = 0x03,
        .name = "SetPeriod",
        .in   = {&wmi_t_uint8,NULL},
        .out  = {&wmi_t_uint16,NULL},
    },
    {}
};

static const struct acer_wmi_method biossetting_methods[] = {
    { // Check password existence.
        .id   = 0x01,
        .name = "CheckPasswordExist",
        .in   = {&wmi_t_string,NULL},
        .out  = {&wmi_t_uint32,&wmi_t_uint32,NULL},
    },
    { // Get power on password status.
        .id   = 0x02,
        .name = "GetPowerOnPasswordStatus",
        .in   = {NULL},
        .out  = {&wmi_t_uint32,&wmi_t_uint32,NULL},
    },
    { // Set power on password status.
        .id   = 0x03,
        .name = "SetPowerOnPasswordStatus",
        .in   = {&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get boot device model name.
        .id   = 0x08,
        .name = "GetBootDeviceModelName",
        .in   = {&wmi_t_string,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_string,&wmi_t_uint32,NULL},
    },
    { // Get boot device serial number.
        .id   = 0x09,
        .name = "GetBootDeviceSerialNumber",
        .in   = {&wmi_t_string,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,&wmi_t_string,NULL},
    },
    { // Get asset tag.
        .id   = 0x0A,
        .name = "GetAssetTag",
        .in   = {NULL},
        .out  = {&wmi_t_string,&wmi_t_uint32,NULL},
    },
    { // Set asset tag.
        .id   = 0x0B,
        .name = "SetAssetTag",
        .in   = {&wmi_t_string,&wmi_t_uint8a,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Load BIOS default.
        .id   = 0x0D,
        .name = "LoadBIOSDefault",
        .in   = {&wmi_t_uint8a,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Load user default.
        .id   = 0x0E,
        .name = "LoadUserDefault",
        .in   = {&wmi_t_uint8a,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get boot sequence.
        .id   = 0x10,
        .name = "GetBootSequence",
        .in   = {NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint32,NULL},
    },
    { // Set boot sequence.
        .id   = 0x11,
        .name = "SetBootSequence",
        .in   = {&wmi_t_uint8a,&wmi_t_uint8a,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get device and port state.
        .id   = 0x12,
        .name = "GetDevicePortState",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint32,&wmi_t_uint32,NULL},
    },
    { // Set device and port state.
        .id   = 0x13,
        .name = "SetDevicePortState",
        .in   = {&wmi_t_uint32,&wmi_t_uint32,&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get UUID.
        .id   = 0x14,
        .name = "GetUUID",
        .in   = {NULL},
        .out  = {&wmi_t_uint32,&wmi_t_string,NULL},
    },
    { // Set UUID.
        .id   = 0x15,
        .name = "SetUUID",
        .in   = {&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_string,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Serial Number.
        .id   = 0x16,
        .name = "GetSerialNumber",
        .in   = {NULL},
        .out  = {&wmi_t_uint32,&wmi_t_string,NULL},
    },
    { // Set Serial Number.
        .id   = 0x17,
        .name = "SetSerialNumber",
        .in   = {&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_string,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get PBA POA status.
        .id   = 0x18,
        .name = "GetPBAPOAStatus",
        .in   = {NULL},
        .out  = {&wmi_t_uint32,&wmi_t_uint32,NULL},
    },
    { // Set PBA POA status.
        .id   = 0x19,
        .name = "SetPBAPOAStatus",
        .in   = {&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,&wmi_t_uint32,NULL},
    },
    { // Get PBA POA transferred data.
        .id   = 0x1A,
        .name = "GetPBAPOAData",
        .in   = {NULL},
        .out  = {&wmi_t_uint32,&wmi_t_uint8a,NULL},
    },
    { // Set PBA POA transferred data.
        .id   = 0x1B,
        .name = "SetPBAPOAData",
        .in   = {&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get Ownership Tag.
        .id   = 0x1C,
        .name = "GetOwnershipTag",
        .in   = {NULL},
        .out  = {&wmi_t_string,&wmi_t_uint32,NULL},
    },
    { // Set Ownership Tag.
        .id   = 0x1D,
        .name = "SetOwnershipTag",
        .in   = {&wmi_t_string,&wmi_t_uint8a,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    {}
};

static const struct acer_wmi_method listbiossettings_methods[] = {
    {}
};

static const struct acer_wmi_method s3resumefunction_methods[] = {
    { //  Get S3 Resume Time . Pass to BIOS.
        .id   = 0x01,
        .name = "GetS3ResumeTime",
        .in   = {&wmi_t_uint8,NULL},
        .out  = {&wmi_t_uint16,NULL},
    },
    {}
};

static const struct acer_wmi_method methodforpowershell_methods[] = {
    { // Set BIOS Setting
        .id   = 0x01,
        .name = "SetBiosSetting",
        .in   = {&wmi_t_string,&wmi_t_string,&wmi_t_string,NULL},
        .out  = {&wmi_t_string,NULL},
    },
    { // Get BIOS Setting
        .id   = 0x02,
        .name = "GetBiosSetting",
        .in   = {&wmi_t_string,&wmi_t_string,NULL},
        .out  = {&wmi_t_string,&wmi_t_string,NULL},
    },
    { // Load BIOS default
        .id   = 0x03,
        .name = "LoadBIOSDefault",
        .in   = {&wmi_t_string,NULL},
        .out  = {&wmi_t_string,NULL},
    },
    { // Load User default
        .id   = 0x04,
        .name = "LoadUserDefault",
        .in   = {&wmi_t_string,NULL},
        .out  = {&wmi_t_string,NULL},
    },
    {}
};

static const struct acer_wmi_method acerbiosconfigurationtool_methods[] = {
    { // Set BIOS Options
        .id   = 0x01,
        .name = "SetBiosOptions",
        .in   = {&wmi_t_uint8a,&wmi_t_uint8a,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get BIOS Options
        .id   = 0x02,
        .name = "GetBiosOptions",
        .in   = {&wmi_t_uint8a,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint32,NULL},
    },
    { // Set BIOS Default Options
        .id   = 0x03,
        .name = "SetBiosDefaultOptions",
        .in   = {&wmi_t_uint8a,&wmi_t_uint8a,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get BIOS Default Options
        .id   = 0x04,
        .name = "GetBiosDefaultOptions",
        .in   = {&wmi_t_uint8a,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint32,NULL},
    },
    { // Get USB Device Filter Status
        .id   = 0x05,
        .name = "GetUSBDeviceFilterStatus",
        .in   = {NULL},
        .out  = {&wmi_t_uint32,&wmi_t_uint8,NULL},
    },
    {}
};

static const struct acer_wmi_method utilityfunction_methods[] = {
    { // Check user supervisor password.
        .id   = 0x01,
        .name = "CheckPassword",
        .in   = {&wmi_t_string,&wmi_t_uint8a,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,&wmi_t_uint32,NULL},
    },
    { // Set user supervisor password.
        .id   = 0x02,
        .name = "SetPassword",
        .in   = {&wmi_t_string,&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_uint8a,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Get BIOS settings.
        .id   = 0x03,
        .name = "GetBIOSSettings",
        .in   = {&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_uint8a,&wmi_t_uint32,NULL},
    },
    { // Set BIOS settings.
        .id   = 0x04,
        .name = "SetBIOSSettings",
        .in   = {&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_uint16,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Set HDD password.
        .id   = 0x05,
        .name = "SetHDDPassword",
        .in   = {&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_uint16,&wmi_t_uint16,&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Dock Port Firmware Programming.
        .id   = 0x06,
        .name = "DockPortFirmwareProgramming",
        .in   = {&wmi_t_uint8,&wmi_t_uint8a,&wmi_t_uint8,&wmi_t_uint8,&wmi_t_uint8,&wmi_t_uint8,&wmi_t_uint8,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Set Acer Diagnostic Status.
        .id   = 0x07,
        .name = "SetAcerDiagnostic",
        .in   = {&wmi_t_uint8,&wmi_t_uint8,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint8,NULL},
    },
    { // Get Acer Diagnostic Status.
        .id   = 0x08,
        .name = "GetAcerDiagnosticStatus",
        .in   = {&wmi_t_uint8,&wmi_t_uint8,NULL},
        .out  = {&wmi_t_uint16,&wmi_t_uint8,&wmi_t_uint8,NULL},
    },
    { // Device Firmware Programming.
        .id   = 0x09,
        .name = "DeviceFWProgramming",
        .in   = {&wmi_t_uint8,&wmi_t_uint8,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint8,NULL},
    },
    { // Get HDD password.
        .id   = 0x0A,
        .name = "GetHDDPassword",
        .in   = {&wmi_t_uint16,&wmi_t_uint16,&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint16,&wmi_t_uint16,&wmi_t_uint8a,&wmi_t_uint32,NULL},
    },
    { // Get LED Indicator.
        .id   = 0x0B,
        .name = "GetLedIndicatorSts",
        .in   = {&wmi_t_uint32,NULL},
        .out  = {&wmi_t_uint64,NULL},
    },
    { // Set LED Indicator.
        .id   = 0x0C,
        .name = "SetLedIndicator",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    { // Set EDID to System.
        .id   = 0x0D,
        .name = "SetEDIDtoSystem",
        .in   = {&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint8,NULL},
    },
    { // Get Second Display Device Status.
        .id   = 0x0E,
        .name = "GetSecondDisplayDeviceStatus",
        .in   = {&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint8,&wmi_t_uint8a,&wmi_t_uint8,NULL},
    },
    { // Set Second Display Device Status.
        .id   = 0x0F,
        .name = "SetSecondDisplayDeviceStatus",
        .in   = {&wmi_t_uint8,&wmi_t_uint8a,NULL},
        .out  = {&wmi_t_uint8a,&wmi_t_uint8,NULL},
    },
    { // Notify WiFi Status
        .id   = 0x10,
        .name = "NotifyWifiStatus",
        .in   = {&wmi_t_uint64,NULL},
        .out  = {&wmi_t_uint32,NULL},
    },
    {}
};

static const size_t acer_wmi_method_count = 89;


static const struct acer_wmi_class acer_wmi_classes[] = {
    { // APGe WMI Event, Version 2.94
        .guid = "676AA15E-6A47-4D9F-A2CC-1E6D18D14026",
        .name = "APGeEvent",
        .methods = &apgeevent_methods,
    },
    { // Sec. WMI Event, Version 2.94
        .guid = "A9D77EF6-55E0-4706-B139-96ACE13F2269",
        .name = "SecEvent",
        .methods = &secevent_methods,
    },
    { // Acer Generic WMI Event, Version 2.94
        .guid = "2E6B3CE2-6A58-4AF2-8767-4640CA8A38E3",
        .name = "AcerGenericEvent",
        .methods = &acergenericevent_methods,
    },
    { // APGe WMI Method, Version 2.94
        .guid = "61EF69EA-865C-4BC3-A502-A0DEBA0CB531",
        .name = "APGeAction",
        .methods = &apgeaction_methods,
    },
    { // Class used to control smart battery, Version 2.94
        .guid = "79772EC5-04B1-4bfd-843C-61E7F77B6CC9",
        .name = "BatteryControl",
        .methods = &batterycontrol_methods,
    },
    { // Class used to Gaming Function, Version 2.94
        .guid = "7A4DDFE7-5B5D-40B4-8595-4408E0CC7F56",
        .name = "AcerGamingFunction",
        .methods = &acergamingfunction_methods,
    },
    { // APGe Secure WMI Method, Version 2.94
        .guid = "9F98130E-3B48-40B3-9402-DE8E160F30CC",
        .name = "DataTrans",
        .methods = &datatrans_methods,
    },
    { // Acer Generic WMI Method, Version 2.94
        .guid = "1EA0BC57-521E-461B-A7A9-5D36F141A82A",
        .name = "AcerGenericMethod",
        .methods = &acergenericmethod_methods,
    },
    { // Class used to Long Run, Version 2.94
        .guid = "79772EC6-04B1-4bfd-843C-61E7F77B6CC9",
        .name = "LongRunFunction",
        .methods = &longrunfunction_methods,
    },
    { // Class used for BIOS settings, Version 2.94
        .guid = "F75F5666-B8B3-4a5d-A91C-7488F62E5637",
        .name = "BIOSSetting",
        .methods = &biossetting_methods,
    },
    { // Data for PowerShell, Version 2.94
        .guid = "FDAE8C0C-6FA2-49C3-87A0-97483BE485F2",
        .name = "ListBIOSSettings",
        .methods = &listbiossettings_methods,
    },
    { // Class used to S3 Resume, Version 2.94
        .guid = "77B0C3A7-F71D-43cb-B749-91CBFF5DDC43",
        .name = "S3ResumeFunction",
        .methods = &s3resumefunction_methods,
    },
    { // Method for PowerShell, Version 2.94
        .guid = "48E699DB-C63C-4472-9468-4B4189905D24",
        .name = "MethodForPowerShell",
        .methods = &methodforpowershell_methods,
    },
    { // Acer BIOS Setting Tool, Version 2.94
        .guid = "4BB53443-488A-430D-A25C-874660E23BDD",
        .name = "AcerBiosConfigurationTool",
        .methods = &acerbiosconfigurationtool_methods,
    },
    { // Class used for utility, Version 2.94
        .guid = "FE1DBBDA-3014-4856-870C-5B3A744BF341",
        .name = "UtilityFunction",
        .methods = &utilityfunction_methods,
    },
    {}
};

static const size_t acer_wmi_class_count = 15;

// MSWmi_MofData, FIRE_TEST_EVENT, WiFi_GenericSensorData

static struct acer_debug debug = {};



const char sep[] = {'\n', ' ', '\t'};

static size_t
WMI_execute_xstring(const struct acer_wmi_entity *wme, const char *in, char **out)
{
    const char *guid;
    u32 method_id;
    size_t len;
    size_t r = 0;

    char *inbuf = kzalloc(strlen(in) + 1, GFP_KERNEL);
    char *const inbuf0 = inbuf;
    strcpy(inbuf, in);

    if (wme->type == ACER_WMI_TYPE_METHOD && wme->class && wme->method) {
        size_t m_len = 0;
        for (int i = 0; wme->method->in[i]; i++) {
            if (wme->method->in[i]->array) {
                m_len += 1024;
            } else {
                m_len += wme->method->in[i]->size;
            }
        }

        guid = wme->class->guid;
        method_id = wme->method->id;

        len = strlen(inbuf) / 2; // works for trailing newline too because it is rounded down 
        if (len > m_len) {
            pr_err("WMI_execute_m: Input too long (%zu/%zu)\n", len, m_len);
            r = -E2BIG;
            goto err1;
        }
        pr_info("WMI_execute_m: C: %s (%s); M: %s (%.2X); I: %s (%zu/%zu)\n", wme->class->name, guid, wme->method->name, method_id, inbuf, len, m_len);
    } else if (wme->type == ACER_WMI_TYPE_CLASS && wme->class) {
        guid = wme->class->guid;

        char *const id_x = inbuf;
        strsep(&inbuf, sep);
    
        if (strlen(id_x) > 8) {
            pr_err("WMI_execute_c: Method id too long, should be u32\n");
            r = -EINVAL;
            goto err1;
        }
        method_id = (u32) strtoul(id_x, NULL, 16);
    
        len = strlen(inbuf) / 2;
        if (len > 8192) {
            pr_err("WMI_execute_c: Input too long (%zu/8192)\n", len);
            r = -E2BIG;
            goto err1;
        }
        pr_info("WMI_execute_c: C: %s (%s); M: %s (%.2X); I: %s (%zu)\n", wme->class->name, guid, id_x, method_id, inbuf, len);
    } else if (wme->type == ACER_WMI_TYPE_ROOT) {
        char *const in_g = inbuf;
        strsep(&inbuf, sep);
        char *const id_x = inbuf;
        strsep(&inbuf, sep);

        const size_t gl = strlen(in_g);
        if (gl != 36) {
            pr_err("WMI_execute_g: Incorrect GUID length: %zu, should be 36\n", gl);
            r = -EINVAL;
            goto err1;
        }
        guid = in_g;

        if (strlen(id_x) > 8) {
            pr_err("WMI_execute_g: Method id too long, should be u32\n");
            r = -EINVAL;
            goto err1;
        }
        method_id = (u32) strtoul(id_x, NULL, 16);

        len = strlen(inbuf) / 2;
        if (len > 8192) {
            pr_err("WMI_execute_g: Input too long (%zu/8192)\n", len);
            r = -E2BIG;
            goto err1;
        }
        pr_info("WMI_execute_g: C: %s; M: %s (%.2X); I: %s (%zu)\n", guid, id_x, method_id, inbuf, len);
    } else {
        pr_err("WMI_execute: Unsupported WMI type: %u\n", wme->type);
        r = -ENOTSUPP;
        goto err1;
    }

    u8 *const data = kzalloc(len, GFP_KERNEL);
    if (hex2bin(data, inbuf, len)) {
        pr_err("WMI_execute: Hex parse error: data\n");
        kfree(data);
        r = -EBADMSG;
        goto err1;
    }

    // convert input to little-endian
    u8 *const data_le = kzalloc(len, GFP_KERNEL);
    for (int i = 0; i < len; i++) {
        data_le[i] = data[(len - 1) - i];
    }

    kfree(data);

	struct acpi_buffer result = { ACPI_ALLOCATE_BUFFER, NULL };
	const struct acpi_buffer input = {
		.length = len,
		.pointer = data_le,
	};

    pr_info("WMI_execute: C: %s; M: %.2X; I: %s (%zu)\n", guid, method_id, inbuf, len);
	const acpi_status status = wmi_evaluate_method(guid, 0, method_id, &input, &result);

    kfree(data_le);

	if (ACPI_FAILURE(status)) {
        pr_err("WMI_execute: ACPI failure: %u\n", status);
		r = -EIO;
        goto err1;
    }

	const union acpi_object *const obj = (union acpi_object *) result.pointer;
    char *tmp;
	if (obj) {
		if (obj->type == ACPI_TYPE_BUFFER) {
            const size_t o_len = obj->buffer.length;
            // output is little-endian, convert to big
            u8 *const buffer_be = kzalloc(o_len, GFP_KERNEL);
            for (int i = 0; i < o_len; i++) {
                buffer_be[i] = obj->buffer.pointer[(o_len - 1) - i];
            }
            tmp = kzalloc(o_len * 2 + 2, GFP_KERNEL);
            bin2hex(tmp, buffer_be, o_len);
            tmp[o_len * 2] = '\n'; // add newline for cat
            kfree(buffer_be);
		} else if (obj->type == ACPI_TYPE_INTEGER) {
			tmp = kzalloc(8 * 2 + 2, GFP_KERNEL);
            sprintf(tmp, "%.2llX\n", obj->integer.value);
		} else {
            pr_err("WMI_execute_r: Unsupported return type: %u\n", obj->type);
            r = -EOPNOTSUPP;
            goto err2;
        }
	}
    pr_info("WMI_execute_r: C: %s; M: %.2X; I: %s; O: %s\n", guid, method_id, inbuf, tmp);

	if (out) {
		*out = tmp;
    }

    err2:
	acpi_os_free(result.pointer);

    err1:
    kfree(inbuf0);
    return r;
}

static struct mutex acer_wmi_mtx;
static wait_queue_head_t acer_wmi_wq;

static ssize_t acer_wmi_read(struct file *filp, char __user *buffer, size_t length, loff_t *offset) {
    if (filp->f_flags & O_NONBLOCK) {
		return -EAGAIN;
	}

    struct acer_wmi_entity *const wme = filp->f_inode->i_private;

    if (wme) {
        if (wait_event_interruptible(acer_wmi_wq, wme->read)) {
            return -EINTR;
        }
        wme->read = false;
        char *ret = wme->ret;
        if (ret) {
            size_t len = strlen(ret);
            len = min(len, length);
            if (copy_to_user(buffer, ret, len)) {
                return -ECOMM;
            }
            return len;
        }
        return -ENODATA;
    }

    return -ENODEV;
}

static ssize_t acer_wmi_write(struct file *filp, const char __user *buffer, size_t length, loff_t *offset) {
    mutex_lock_interruptible(&acer_wmi_mtx);
    struct acer_wmi_entity *const wme = filp->f_inode->i_private;

    size_t r = -ENODEV;
    if (wme) {
        char *in = kzalloc(length + 1, GFP_KERNEL);
        char *const in0 = in;
        char *out;
        if (!copy_from_user(in0, buffer, length)) {
            r = WMI_execute_xstring(wme, in, &out);
            if (!r) {
                char *const ret = wme->ret;
                if (ret) {
                    kfree(ret);
                }
                if (wme->type == ACER_WMI_TYPE_METHOD) {
                    wme->ret = out;
                    wme->read = true;

                    char *const id_s = kzalloc(4 * 2 + 3 + 1, GFP_KERNEL);
                    sprintf(id_s, "%.2X(", wme->method->id);

                    if (wme->class_wme) {
                        char *const c_out = kzalloc(strlen(id_s) + strlen(wme->method->name) + 2 + strlen(out) + 1, GFP_KERNEL);
                        strcat(c_out, id_s);
                        strcat(c_out, wme->method->name);
                        strcat(c_out, ") ");
                        strcat(c_out, out);

                        char *const c_ret = wme->class_wme->ret;
                        if (c_ret) {
                            kfree(c_ret);
                        }
                        wme->class_wme->ret = c_out;
                        wme->class_wme->read = true;
                    }

                    char *const r_out = kzalloc(strlen(wme->class->guid) + 1 + strlen(wme->class->name) + 2 + strlen(id_s) + strlen(wme->method->name) + 2 + strlen(out) + 1, GFP_KERNEL);
                    strcat(r_out, wme->class->guid);
                    strcat(r_out, "(");
                    strcat(r_out, wme->class->name);
                    strcat(r_out, ") ");
                    strcat(r_out, id_s);
                    strcat(r_out, wme->method->name);
                    strcat(r_out, ") ");
                    strcat(r_out, out);
                    kfree(id_s);

                    char *const r_ret = debug.root_wme->ret;
                    if (r_ret) {
                        kfree(r_ret);
                    }
                    debug.root_wme->ret = r_out;
                    debug.root_wme->read = true;
                } else if (wme->type == ACER_WMI_TYPE_CLASS) {
                    strsep(&in, sep);

                    char *const c_out = kzalloc(strlen(in0) + 1 + strlen(out) + 1, GFP_KERNEL);
                    strcat(c_out, in0);
                    strcat(c_out, " ");
                    strcat(c_out, out);

                    kfree(out);

                    wme->ret = c_out;
                    wme->read = true;

                    char *const r_out = kzalloc(strlen(wme->class->guid) + 1 + strlen(wme->class->name) + 2 + strlen(c_out) + 1, GFP_KERNEL);
                    strcat(r_out, wme->class->guid);
                    strcat(r_out, "(");
                    strcat(r_out, wme->class->name);
                    strcat(r_out, ") ");
                    strcat(r_out, c_out);

                    char *const r_ret = debug.root_wme->ret;
                    if (r_ret) {
                        kfree(r_ret);
                    }
                    debug.root_wme->ret = r_out;
                    debug.root_wme->read = true;
                } else if (wme->type == ACER_WMI_TYPE_ROOT) {
                    strsep(&in, sep);
                    char *const id_x = in;
                    strsep(&in, sep);

                    char *const r_out = kzalloc(strlen(in0) + 1 + strlen(id_x) + 1 + strlen(out) + 1, GFP_KERNEL);
                    strcat(r_out, in0);
                    strcat(r_out, " ");
                    strcat(r_out, id_x);
                    strcat(r_out, " ");
                    strcat(r_out, out);

                    kfree(out);

                    wme->ret = r_out;
                    wme->read = true;
                } else {
                    wme->ret = out;
                    wme->read = true;
                }
                wake_up_interruptible(&acer_wmi_wq);
                r = length;
            }
        }
        kfree(in0);
        r = -ECOMM;
    }

    mutex_unlock(&acer_wmi_mtx);
    return r;
}

const struct debugfs_short_fops acer_wmi_fops = {
    .read = acer_wmi_read,
    .write = acer_wmi_write,
};

static void __init create_debugfs(void)
{
	debug.root = debugfs_create_dir("acer_wmi_debug", NULL);

    debug.entities = kzalloc(sizeof(struct acer_wmi_entity) * (acer_wmi_method_count + acer_wmi_class_count + 2), GFP_KERNEL);

    int cnt = 0;
    struct acer_wmi_entity *const cla = &(debug.entities[cnt]);
    cnt++;
    cla->type = ACER_WMI_TYPE_ROOT;
    cla->dir = debug.root;
    cla->file = debugfs_create_file("_", 0644, debug.root, cla, &acer_wmi_fops);
    debug.root_wme = cla;
	for (int i = 0; acer_wmi_classes[i].name; i++) {
	    const struct acer_wmi_class *const cl = &(acer_wmi_classes[i]);
        struct dentry *const cdir = debugfs_create_dir(cl->name, debug.root);
        struct acer_wmi_entity *const cle = &(debug.entities[cnt]);
        cnt++;
        cle->type = ACER_WMI_TYPE_CLASS;
        cle->class = cl;
        cle->dir = cdir;
        if (wmi_has_guid(cl->guid)) {
            cle->file = debugfs_create_file(cl->guid, 0644, cdir, cle, &acer_wmi_fops);
	        for (int j = 0; (*(cl->methods))[j].name; j++) {
                const struct acer_wmi_method *const mt = &((*(cl->methods))[j]);
                struct acer_wmi_entity *const mte = &(debug.entities[cnt]);
                cnt++;
                mte->type = ACER_WMI_TYPE_METHOD;
                mte->method = mt;
                mte->class = cl;
                mte->class_wme = cle;
                mte->dir = cdir;
                mte->file = debugfs_create_file(mt->name, 0644, cdir, mte, &acer_wmi_fops);
            }
        }
    }
}

static int __init acer_wmi_init(void)
{
	pr_info("Acer WMI Debug\n");

    mutex_init(&acer_wmi_mtx);
    init_waitqueue_head(&acer_wmi_wq);

	create_debugfs();

	return 0;
}

static void __exit acer_wmi_exit(void)
{
	debugfs_remove_recursive(debug.root);

    for (int i = 0; debug.entities[i].type; i++) {
        char *const ret = debug.entities[i].ret;
        if (ret) {
            kfree(ret);
        }
    }

    kfree(debug.entities);

	pr_info("Acer WMI Debug unloaded\n");
}

module_init(acer_wmi_init);
module_exit(acer_wmi_exit);
